### ISSUE TITLE
Data Issue

### ISSUE THREAD

**Issue by Abbaskhan321** [fmdl/odoo_apps_public#14]
Partner, Aged, opened Ledger data not show. If i click on view lines button so data not show in line View,PDF View and Excel View. Please help me asap.

**Comment by fmdl** [comment]
Have you configure the field Third party on account ?

**Comment by Abbaskhan321** [comment]
Thanks for quick reply @fmdl .

**Comment by fmdl** [comment]
in each accounts

**Comment by Abbaskhan321** [comment]
Thannks dear my issue is solved.
