### ISSUE TITLE
General Ledger Line table grows extremely large slowing down Odoo

### ISSUE THREAD

**Issue by piqoni** [fmdl/odoo_apps_public#9]
We had performance issues on our instance and found out the root cause was the the reports being generated. 

We found out table account_report_standard_ledger_line had ~56 million rows
Thing went back to normal after we truncated the table:
```
truncate account_report_standard_ledger_line cascade
```
Which will cascade into:
```
NOTICE:  truncate cascades to table "account_report_standard_ledger_report"
NOTICE:  truncate cascades to table "table_standard_report_line_total"
NOTICE:  truncate cascades to table "account_report_standard_ledger_report_object"
NOTICE:  truncate cascades to table "account_report_standard_ledger"
NOTICE:  truncate cascades to table "table_standard_report_partner"
NOTICE:  truncate cascades to table "account_journal_account_report_standard_ledger_rel"
NOTICE:  truncate cascades to table "account_analytic_account_account_report_standard_ledger_rel"
NOTICE:  truncate cascades to table "table_standard_report_accounts"
NOTICE:  truncate cascades to table "account_report_standard_ledger_res_partner_rel"
NOTICE:  truncate cascades to table "account_account_account_report_standard_ledger_rel"
```

We're thinking to put a cron and doing this daily. Do you have any other suggestion? Wouldn't those tables grow indefinitely otherwise.

**Comment by fmdl** [comment]
Hi this table is a transient, odoo clean every day all transients table, by this cron http://381006-11-0-5a2555.runbot11.odoo.com/web?debug#id=1&view_type=form&model=ir.cron&action=10&menu_id=4

check in your logs if the cron exceute normally.

**Comment by piqoni** [comment]
Thanks, yes the cron is running but apparently they produced a lot of reports and the cron ran daily. 

Closing this.
